version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    #network_mode: host
    volumes:
      - /home/serveradmin/homebridge/data:/homebridge
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '1'
    healthcheck:
      test: curl --fail localhost:8581 || exit 1
      interval: 60s
      retries: 5
      start_period: 300s
      timeout: 2s
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.homebridge.entrypoints=http'
      - 'traefik.http.routers.homebridge.rule=Host(`homebridge.local.gregdyer.ca`)'
      - 'traefik.http.middlewares.homebridge-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.homebridge.middlewares=homebridge-https-redirect'
      - 'traefik.http.routers.homebridge-secure.entrypoints=https'
      - 'traefik.http.routers.homebridge-secure.rule=Host(`homebridge.local.gregdyer.ca`)'
      - 'traefik.http.routers.homebridge-secure.tls=true'
      - 'traefik.http.routers.homebridge-secure.service=homebridge'
      - 'traefik.http.services.homebridge.loadbalancer.server.port=8581'
      - 'traefik.docker.network=proxy'

networks:
  proxy:
    external: true
