version: '3'
services:
  handbrake:
    image: jlesage/handbrake
    ports:
      - '5800:5800'
    volumes:
      - '/home/serveradmin/handbrake/config:/config:rw'
      - '/home/serveradmin/handbrake/storage:/storage:ro'
      - '/mnt/media/handbrake/watch:/watch:rw'
      - '/mnt/media/handbrake/output:/output:rw'
    environment:
      - AUTOMATED_CONVERSION_PRESET=Custom/1080p
      - AUTOMATED_CONVERSION_FORMAT=m4v
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.handbrake.entrypoints=http'
      - 'traefik.http.routers.handbrake.rule=Host(`handbrake.local.gregdyer.ca`)'
      - 'traefik.http.middlewares.handbrake-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.handbrake.middlewares=handbrake-https-redirect'
      - 'traefik.http.routers.handbrake-secure.entrypoints=https'
      - 'traefik.http.routers.handbrake-secure.rule=Host(`handbrake.local.gregdyer.ca`)'
      - 'traefik.http.routers.handbrake-secure.tls=true'
      - 'traefik.http.routers.handbrake-secure.service=handbrake'
      - 'traefik.http.services.handbrake.loadbalancer.server.port=5800'
      - 'traefik.docker.network=proxy'

networks:
  proxy:
    external: true
