---
version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=warning
      - TZ=America/Vancouver
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/serveradmin/overseerr/config:/app/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
