---
version: '2.1'
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=America/Vancouver
    ports:
      - '8191:8191'
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
