events {}

stream {
    # Kubernetes API
    upstream k3s_api {
        server 192.168.0.66:6443;
        server 192.168.0.67:6443;
    }

    # Rancher HTTPS (Traffic for the UI)
    upstream rancher_https {
        server 192.168.0.66:443;
        server 192.168.0.67:443;
    }

    server {
        listen 6443;
        proxy_pass k3s_api;
    }

    server {
        listen 443;
        proxy_pass rancher_https;
    }
}
