---
version: '2.1'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /home/serveradmin/sonarr/config:/config
      - /mnt/media/Plex/TV Shows:/tv #optional
      - /mnt/media/transmission/downloads/completed:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.sonarr.entrypoints=http'
      - 'traefik.http.routers.sonarr.rule=Host(`sonarr.local.gregdyer.ca`)'
      - 'traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.sonarr.middlewares=sonarr-https-redirect'
      - 'traefik.http.routers.rasonarrdarr-secure.entrypoints=https'
      - 'traefik.http.routers.sonarr-secure.rule=Host(`sonarr.local.gregdyer.ca`)'
      - 'traefik.http.routers.sonarr-secure.tls=true'
      - 'traefik.http.routers.sonarr-secure.service=sonarr'
      - 'traefik.http.services.sonarr.loadbalancer.server.port=8989'
      - 'traefik.docker.network=proxy'

networks:
  proxy:
    external: true
