---
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Vancouver
    ports:
      - 5065:5055
    volumes:
      - /home/serveradmin/jellyseerr/config:/app/config
    restart: unless-stopped
