---
version: '2.1'
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /home/serveradmin/radarr/config:/config
      - /mnt/media/Plex/Movies:/movies #optional
      - /mnt/media/transmission/downloads/completed:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.radarr.entrypoints=http'
      - 'traefik.http.routers.radarr.rule=Host(`radarr.local.gregdyer.ca`)'
      - 'traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.radarr.middlewares=radarr-https-redirect'
      - 'traefik.http.routers.radarr-secure.entrypoints=https'
      - 'traefik.http.routers.radarr-secure.rule=Host(`radarr.local.gregdyer.ca`)'
      - 'traefik.http.routers.radarr-secure.tls=true'
      - 'traefik.http.routers.radarr-secure.service=radarr'
      - 'traefik.http.services.radarr.loadbalancer.server.port=7878'
      - 'traefik.docker.network=proxy'

networks:
  proxy:
    external: true
