---
version: '2.1'
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /home/serveradmin/lidarr/config:/config
      - /mnt/media/Plex/Music:/music #optional
      - /mnt/media/downloads:/downloads #optional
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.lidarr.entrypoints=http'
      - 'traefik.http.routers.lidarr.rule=Host(`lidarr.local.gregdyer.ca`)'
      - 'traefik.http.middlewares.lidarr-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.lidarr.middlewares=lidarr-https-redirect'
      - 'traefik.http.routers.lidarr-secure.entrypoints=https'
      - 'traefik.http.routers.lidarr-secure.rule=Host(`lidarr.local.gregdyer.ca`)'
      - 'traefik.http.routers.lidarr-secure.tls=true'
      - 'traefik.http.routers.lidarr-secure.service=lidarr'
      - 'traefik.http.services.lidarr.loadbalancer.server.port=8686'
      - 'traefik.docker.network=proxy'

networks:
  proxy:
    external: true
