---
- hosts: all
  become: true
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: yes
      tags: ['setup', 'update']

- hosts: pi
  become: true
  tasks:
    - name: Setup NUT Server
      include_tasks: roles/nut/main.yml
      tags: ['nut', 'setup']
