---
- hosts: all
  become: true
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: yes
      tags: ['setup', 'update']

- hosts: vms
  become: true
  tasks:
    - name: QEMU guest agent
      apt:
        name: qemu-guest-agent
        state: present
      tags: ['setup']

- hosts: pi
  become: true
  tasks:
    - name: Setup NUT Server
      include_tasks: roles/nut/main.yml
      tags: ['nut']
    - name: Setup NUT Web Server
      include_tasks: roles/nut-web/main.yml
      tags: ['nut']
