# ---
# version: '3.8'
# services:
#   ollama:
#     image: ollama/ollama:latest
#     ports:
#       - 11434:11434
#     volumes:
#       - /home/serveradmin/ollama/data:/root/.ollama
#     container_name: ollama
#     # pull_policy: always
#     # tty: true
#     # network_mode: host
#     restart: unless-stopped
#     environment:
#       - OLLAMA_KEEP_ALIVE=24h
#       - OLLAMA_HOST=0.0.0.0
#     networks:
#       - ollama-docker

#   ollama-webui:
#     image: ghcr.io/open-webui/open-webui:main
#     container_name: ollama-webui
#     # network_mode: host
#     volumes:
#       - /home/serveradmin/ollama/web:/app/backend/data
#     depends_on:
#       - ollama
#     ports:
#       - 8080:8080
#     environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
#       - OLLAMA_BASE_URLS=http://host.docker.internal:11434 #comma separated ollama hosts
#       # - ENV=dev
#       - WEBUI_AUTH=False
#       - WEBUI_NAME=valiantlynx AI
#       - WEBUI_URL=http://localhost:8080
#       - WEBUI_SECRET_KEY=t0p-s3cr3t
#     extra_hosts:
#       - host.docker.internal:host-gateway
#     restart: unless-stopped
#     networks:
#       - ollama-docker

# networks:
#   ollama-docker:
#     external: false
---
version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - /home/serveradmin/ollama/data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    # network_mode: host
    ports:
      - '8080:8080'
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://192.68.0.63:11434 #comma separated ollama hosts
      - WEBUI_AUTH=False

    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  open-webui: {}
